config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :dataslates
end

app/models/concerns/picturable.rb
module Picturable
  extend ActiveSupport::Concern

  included do 
    has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/:style/missing.png"
    validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  end
end

app/models/dataslate.rb
class Dataslate < ActiveRecord::Base
  include Picturable

  has_many :dataslate_sources
  has_many :dataslate_factions
  has_many :sources, through: :dataslate_sources
  has_many :factions, through: :dataslate_factions

  scope :role, ->(role_name) { where(role: role_name) }

  def most_recent_source
    sources.order(published: :desc).first
  end

  def previous_sources
    sources.order(published: :desc).offset(1)
  end
end

app/models/dataslate_faction.rb
class DataslateFaction < ActiveRecord::Base
  validates :dataslate_id, :faction_id, presence: true

  belongs_to :dataslate
  belongs_to :faction
end

app/models/dataslate_source.rb
class DataslateSource < ActiveRecord::Base
  validates :dataslate_id, :source_id, presence: true

  belongs_to :dataslate
  belongs_to :source
end

app/models/faction.rb
class Faction < ActiveRecord::Base
  include Picturable

  has_many :dataslate_factions
  has_many :dataslates, through: :dataslate_factions
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :source
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :dataslate_sources
  has_many :dataslates, through: :dataslate_sources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dataslates_controller.rb
class DataslatesController < ApplicationController
  before_action :set_dataslate, only: [:show, :edit, :update, :destroy]

  # GET /dataslates
  # GET /dataslates.json
  def index
    if params[:faction_id]
      faction = Faction.find_by_id(params[:faction_id])
      @dataslates = faction.dataslates if faction 
    end
  end

  # GET /dataslates/1
  # GET /dataslates/1.json
  def show
  end

  # GET /dataslates/new
  def new
    @dataslate = Dataslate.new
  end

  # GET /dataslates/1/edit
  def edit
  end

  # POST /dataslates
  # POST /dataslates.json
  def create
    @dataslate = Dataslate.new(dataslate_params)

    respond_to do |format|
      if @dataslate.save
        format.html { redirect_to @dataslate, notice: 'Dataslate was successfully created.' }
        format.json { render :show, status: :created, location: @dataslate }
      else
        format.html { render :new }
        format.json { render json: @dataslate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dataslates/1
  # PATCH/PUT /dataslates/1.json
  def update
    respond_to do |format|
      if @dataslate.update(dataslate_params)
        format.html { redirect_to @dataslate, notice: 'Dataslate was successfully updated.' }
        format.json { render :show, status: :ok, location: @dataslate }
      else
        format.html { render :edit }
        format.json { render json: @dataslate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dataslates/1
  # DELETE /dataslates/1.json
  def destroy
    @dataslate.destroy
    respond_to do |format|
      format.html { redirect_to dataslates_url, notice: 'Dataslate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataslate
      @dataslate = Dataslate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dataslate_params
      params[:dataslate]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @factions = Faction.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dataslates/_form.html.haml
= form_for @dataslate do |f|
  - if @dataslate.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dataslate.errors.count, "error")} prohibited this dataslate from being saved:"
      %ul
        - @dataslate.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/dataslates/edit.html.haml
%h1 Editing dataslate

= render 'form'

= link_to 'Show', @dataslate
\|
= link_to 'Back', dataslates_path

app/views/dataslates/index.html.haml
%h1 Listing dataslates

%table
  %thead
    %tr
      %th Name
      %th Role
      %th
      %th
      
  %tbody
    - @dataslates.each do |dataslate|
      %tr
        %td= link_to dataslate.title, dataslate
        %td= dataslate.role
        %td= link_to 'Edit', edit_dataslate_path(dataslate)
        %td= link_to 'Destroy', dataslate, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dataslate', new_dataslate_path

app/views/dataslates/new.html.haml
%h1 New dataslate

= render 'form'

= link_to 'Back', dataslates_path

app/views/dataslates/show.html.haml
%p#notice= notice

%h1= @dataslate.title
%p= @dataslate.role
%h2 Sources
%ul
  - @dataslate.sources.each do |source|
    %li= source.title

= link_to 'Edit', edit_dataslate_path(@dataslate)
\|
= link_to 'Back', dataslates_path

app/views/home/index.html.haml
%h1 Sources
%nav
  %ul
    - @factions.each do |faction|
      %li
        %a.faction{href: '#', data: {faction_id: faction.id}}= faction.name
        = image_tag faction.picture.url(:thumb)

%h2 Dataslates
%nav#dataslates

%h2 Dataslate Info
#dataslate

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Warfaqs
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag params[:controller]
    = csrf_meta_tags
  %body
    = yield